server:
  url: http://localhost:5001
  cors: true
  pretty_print: true
  mimetype: application/json
  encoding: utf-8
  language: en-US

metadata:
    identification:
        title:
            en: pygeoapi default instance
            fr: instance par défaut de pygeoapi
        description:
            en: pygeoapi provides an API to geospatial data
            fr: pygeoapi fournit une API aux données géospatiales
        keywords:
            en:
                - geospatial
                - data
                - api
            fr:
                - géospatiale
                - données
                - api
        keywords_type: theme
        terms_of_service: https://creativecommons.org/licenses/by/4.0/
        url: https://example.org
    license:
        name: CC-BY 4.0 license
        url: https://creativecommons.org/licenses/by/4.0/
    provider:
        name: Organization Name
        url: https://pygeoapi.io
    contact:
        name: Lastname, Firstname
        position: Position Title
        address: Mailing Address
        city: City
        stateorprovince: Administrative Area
        postalcode: Zip or Postal Code
        country: Country
        phone: +xx-xxx-xxx-xxxx
        fax: +xx-xxx-xxx-xxxx
        email: you@example.org
        url: Contact URL
        hours: Mo-Fr 08:00-17:00
        instructions: During hours of service. Off on weekends.
        role: pointOfContact

logging:
  level: DEBUG
  logfile: /tmp/pygeoapi.log

resources:
  places_tiger:
    type: collection
    title: "Lugares TIGER"
    description: "Datos geoespaciales de la tabla TIGER"
    keywords:
      - "lugares"
      - "geodatos"
    extents:
      spatial:
        bbox: [-180, -90, 180, 90]
        crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
    providers:
      - type: feature
        name: PostgreSQL
        data:
          host: 127.0.0.1:5432  # Dirección del contenedor de PostgreSQL
          port: 5432
          dbname: geoexample
          user: root
          password: root
          table: tiger.place  # Aquí defines la tabla 'tiger.place' (reemplaza con el nombre de la tabla correcta)
        id_field: gid
        geom_field: the_geom
        crs:
          - http://www.opengis.net/def/crs/EPSG/0/4269
        storage_crs: http://www.opengis.net/def/crs/EPSG/0/4269
