name: Deploy and Test All Repos

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout TIER_WEB
        uses: actions/checkout@v4
        with:
          path: TIER_WEB
          
      - name: Configurar rama predeterminada
        run: git config --global init.defaultBranch main
        
      - name: Checkout TIER_APP
        uses: actions/checkout@v4
        with:
          repository: UNIZAR-30249-2025-PMPJ/TIER_APP
          token: ${{ secrets.PAT_ACTIONS }}
          path: TIER_APP

      - name: Checkout TIER_DB
        uses: actions/checkout@v4
        with:
          repository: UNIZAR-30249-2025-PMPJ/TIER_DB
          token: ${{ secrets.PAT_ACTIONS }}
          path: TIER_DB

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies and build TIER_WEB
        run: |
          cd TIER_WEB
          echo "RABBITMQ_URL=${{ secrets.RABBITMQ_URL }}" >> .env
          npm install
          npm start &
          cd ..
      - name: Install dependencies and build TIER_DB
        run: |
          cd TIER_DB
          docker compose up -d
          cd ..

      - name: Wait for services to start
        run: sleep 10s
        
      - name: Install dependencies and build TIER_APP
        run: |
          cd TIER_APP
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
          echo "RABBITMQ_URL=${{ secrets.RABBITMQ_URL }}" >> .env
          npm install
          npx prisma migrate reset
          npm start &
          cd ..

      - name: Install newman (Postman CLI)
        run: npm install -g newman

      - name: Run Postman tests
        run: newman run Lab.postman_collection.json --reporters cli
